[package]
name = "firecore-pokedex"
version = "0.3.0-beta.1"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"
description = "Pokemon FireRed Clone Pokedex dependency"
readme = "README.md"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
codegen-units = 1
lto = true

[dependencies]
serde = { version = "1.0", features = ["derive"] }

dashmap = "4.0"
smallvec = { version = "1.6", features = ["serde"] }

lazy_static = "1.4"

quad-rand = "0.2.1" # Use same random as main crate