[package]
name = "firecore-pokedex"
version = "0.4.0-beta.1"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"
description = "Pokemon FireRed Clone Pokedex dependency"
readme = "README.md"
publish = false

[profile.release]
codegen-units = 1
lto = true

[dependencies]

### Specifications

firecore-pokedex-lib = { git = "https://github.com/DoNotDoughnut/firecore-pokedex-lib" }
# firecore-pokedex-lib = { path = "../firecore-pokedex-lib" }

firecore-rand = { git = "https://github.com/DoNotDoughnut/firecore-rand" }


### Collections

smallvec = { version = "1.6", features = ["serde"] }
ahash = { version = "0.7", features = ["serde"] }

### Other

serde = { version = "1.0", features = ["derive"] }