[package]
name = "firecore-pokedex"
version = "0.0.1" # 0.5.0-beta.2021-08-22
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"
description = "A pokedex library"
repository = "https://github.com/DoNotDoughnut/firecore-pokedex/"
readme = "README.md"

[dependencies]
serde = { version = "1", features = ["derive"] }
rand = { version = "0.8", default-features = false }
arrayvec = { version = "0.5", features = ["serde"] }
tinystr = { version = "0.4", features = ["serde"] }
hashbrown = { version = "0.11", features = ["serde"] }
