[package]
name = "firecore-pokedex"
version = "0.3.0-beta.2"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"
description = "Pokemon FireRed Clone Pokedex dependency"
readme = "README.md"
publish = false

[profile.release]
codegen-units = 1
lto = true

[dependencies]

### Specifications

firecore-pokedex-lib = { git = "https://github.com/DoNotDoughnut/firecore-pokedex-lib" }
#firecore-pokedex-lib = { path = "../firecore-pokedex-lib" }

### Collections

smallvec = { version = "1.6", features = ["serde"] }
dashmap = "4.0"

### Other

serde = { version = "1.0", features = ["derive"] }

lazy_static = "1.4"

quad-rand = "0.2.1" # Use same random as main crate