[package]
name = "firecore-pokedex"
version = "0.5.0-beta.2021-08-15"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"
description = "A pokedex library"
readme = "README.md"
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rand = { version = "0.8", default-features = false }
arrayvec = { version = "0.5", features = ["serde"] }
tinystr = { version = "0.4", features = ["serde"] }
hashbrown = { version = "0.11", features = ["serde"] }
log = "0.4"
