[package]
name = "firecore-pokedex"
version = "0.4.0-beta.1"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"
description = "Pokemon FireRed Clone Pokedex dependency"
readme = "README.md"
publish = false

[profile.release]
codegen-units = 1
lto = true

[dependencies]

### Specifications

firecore-pokedex-lib = { path = "./lib" }

firecore-util = { git = "https://github.com/DoNotDoughnut/firecore-util", default-features = false, features = ["random", "smallvec", "hash"] }

serde = { version = "1.0", features = ["derive"] }

[workspace]
members = [
    "lib",
    "builder"
]