[package]
name = "firecore-pokedex"
version = "0.5.0-beta.2021-07-27"
authors = ["Rhys Holloway <rhyswilliamholloway@gmail.com>"]
edition = "2018"
description = "Pokemon FireRed Clone Pokedex dependency"
readme = "README.md"
publish = false

[features]
default = []
stackcount = ["itoa"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rand = { version = "0.8" }
arrayvec = { version = "0.5", features = ["serde"] }
tinystr = { version = "0.4", features = ["serde"] }
hashbrown = "0.11"
rhai = "1"
itoa = { version = "0.4", optional = true }